INSERT INTO CATEGORIA c (c.NOMCAT, c.ESTCAT) VALUES ('Gaseosas', 'A');
INSERT INTO CATEGORIA c (c.NOMCAT, c.ESTCAT) VALUES ('Chocolates', 'A');
INSERT INTO CATEGORIA c (c.NOMCAT, c.ESTCAT) VALUES ('Snacks', 'A');
INSERT INTO CATEGORIA c (c.NOMCAT, c.ESTCAT) VALUES ('Dulces', 'A');
INSERT INTO CATEGORIA c (c.NOMCAT, c.ESTCAT) VALUES ('Galletas', 'A');